/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-bright": "#f6faff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#261a00",
        "primary": "#005bbf",
        "inverse-primary": "#adc7ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#89fa9b",
        "on-primary-fixed-variant": "#004493",
        "on-primary-fixed": "#001a41",
        "background": "#f6faff",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#e4e9ee",
        "secondary": "#006e2c",
        "surface-variant": "#dee3e8",
        "tertiary-fixed": "#ffdfa0",
        "on-surface": "#171c20",
        "surface-container-low": "#f0f4fa",
        "on-secondary-container": "#00722f",
        "primary-fixed-dim": "#adc7ff",
        "on-tertiary-container": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-dim": "#d6dae0",
        "tertiary-fixed-dim": "#fbbc05",
        "surface-container": "#eaeef4",
        "error-container": "#ffdad6",
        "tertiary": "#795900",
        "primary-container": "#1a73e8",
        "on-background": "#171c20",
        "outline-variant": "#c1c6d6",
        "surface-tint": "#005bc0",
        "surface-container-highest": "#dee3e8",
        "on-secondary-fixed": "#002108",
        "surface": "#f6faff",
        "secondary-container": "#86f898",
        "inverse-surface": "#2c3135",
        "secondary-fixed-dim": "#6ddd81",
        "tertiary-container": "#987000",
        "on-surface-variant": "#414754",
        "inverse-on-surface": "#edf1f7",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-primary-container": "#ffffff",
        "outline": "#727785",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005320",
        navy: {
          950: '#0A1931',
          800: '#1A3D63',
          500: '#4A7FA7',
          200: '#B3CFE5',
          50:  '#F6FAFD',
        },
      },
      spacing: {
        "margin-desktop": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
